<?php

return array (
  'name' => 'BlueAdmin',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '192.168.1.1
192.168.1.2',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'wechat' => 'Wechat',
    'example' => 'Example',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'wechat_appid' => 'wxd0e450f42accad28',
  'wechat_appsecret' => '498fa4171c09a1f533e3dfc69be6f6ca',
  'wechat_type' => '0',
  'wechat_sql_hostname' => ' ',
  'wechat_sql_dbname' => ' ',
  'wechat_sql_username' => ' ',
  'wechat_sql_password' => ' ',
  'wechat_sql_ticket_field' => ' ',
  'wechat_sql_ticket_overtime' => ' ',
  'wechat_sql_ticket_where' => ' ',
  'wechat_sql_token_field' => ' ',
  'wechat_sql_token_overtime' => ' ',
  'wechat_sql_token_where' => ' ',
  'wechat_file_ticket_dir' => ' ',
  'wechat_file_token_dir' => ' ',
  'wechat_file_token_field' => ' ',
  'wechat_file_token_overtime' => ' ',
  'wechat_file_ticket_field' => ' ',
  'wechat_file_ticket_overtime' => ' ',
  'wechat_sql_token_table' => ' ',
  'wechat_sql_ticket_table' => ' ',
  'wechat_prjid' => ' ',
);